# Actividad 1. Obtención y preparación de datos desde Hugging Face

En esta actividad se utiliza el dataset Iris, disponible en Hugging Face, para trabajar con datos mediante Python y pandas.

El proceso consiste en cargar la información, revisar su estructura, aplicar cuatro transformaciones y generar un archivo de texto con el resumen de los datos procesados.

In [16]:
from hf_dataset_loader import HFDatasetLoader
from dataset_summarizer import DatasetSummarizer

import pandas as pd

In [17]:
loader = HFDatasetLoader("scikit-learn/iris", split="train")
df_original = loader.cargar_datos()

df_original.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
print("Dimensiones del dataset:", df_original.shape)

print("\nTipos de datos:")
print(df_original.dtypes)

print("\nValores nulos:")
print(df_original.isnull().sum())

Dimensiones del dataset: (150, 6)

Tipos de datos:
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

Valores nulos:
Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

### Transformación 1. Renombrar columnas

Se cambian los nombres de las columnas para facilitar la lectura y el manejo de los datos. Se conservan los valores originales del dataset.

In [19]:

df_transformado = df_original.rename(columns={
    "Id": "id",
    "SepalLengthCm": "largo_sepalo",
    "SepalWidthCm": "ancho_sepalo",
    "PetalLengthCm": "largo_petalo",
    "PetalWidthCm": "ancho_petalo",
    "Species": "especie"
})

df_transformado.head()

   id  largo_sepalo  ancho_sepalo  largo_petalo  ancho_petalo      especie
0   1           5.1           3.5           1.4           0.2  Iris-setosa
1   2           4.9           3.0           1.4           0.2  Iris-setosa
2   3           4.7           3.2           1.3           0.2  Iris-setosa
3   4           4.6           3.1           1.5           0.2  Iris-setosa
4   5           5.0           3.6           1.4           0.2  Iris-setosa

### Transformación 2. Filtrar registros

Se seleccionan las flores que tienen una longitud de pétalo mayor a 2 cm. Con este filtro se reduce la cantidad de registros y se conservan únicamente los que cumplen la condición.

In [20]:

df_transformado = df_transformado[
    df_transformado["largo_petalo"] > 2
].copy()

print("Registros después del filtro:", len(df_transformado))

df_transformado.head()

Registros después del filtro: 100

,id,largo_sepalo,ancho_sepalo,largo_petalo,ancho_petalo,especie
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor

### Transformación 3. Crear una columna calculada

Se agrega una nueva columna llamada `area_petalo`, calculada al multiplicar el largo por el ancho del pétalo. Esto permite obtener una medida aproximada de su superficie.

In [21]:

df_transformado["area_petalo"] = (
    df_transformado["largo_petalo"] * df_transformado["ancho_petalo"]
).round(2)

print("Dimensiones del DataFrame:", df_transformado.shape)

df_transformado.head()

Dimensiones del DataFrame: (100, 7)

,id,largo_sepalo,ancho_sepalo,largo_petalo,ancho_petalo,especie,area_petalo
50,51,7.0,3.2,4.7,1.4,Iris-versicolor,6.58
51,52,6.4,3.2,4.5,1.5,Iris-versicolor,6.75
52,53,6.9,3.1,4.9,1.5,Iris-versicolor,7.35
53,54,5.5,2.3,4.0,1.3,Iris-versicolor,5.20
54,55,6.5,2.8,4.6,1.5,Iris-versicolor,6.90